### ISSUE TITLE
followed 等の値が取れない

### ISSUE THREAD

**Issue by Minyus** [6syun9/twitter_manager#5]
## 症状

以下の変数の値がうまく取れず、同じ値になってしまいます。

- followed = False　（フォローされていてもいなくても同じ）
- joined_list = []
- follower_number = 9999999
- followee_number = 9999999

これら以外の変数についてはそれらしい値を取得できているようです。

![image](https://user-images.githubusercontent.com/33908456/63242402-d9afdc80-c289-11e9-9af6-9836767cd90c.png)

## 再現手順：

README.mdどおり`data_manager.py`を実行

```
python data_manager.py --follower_update --list_update --list_user_update --df_update --user_json_update=1
```

## 環境：
tweepy==3.8.0
Python 3.6.8
Ubuntu 18.04.3 LTS

**Comment by vaaaaanquish** [comment]
確認します

**Comment by vaaaaanquish** [comment]
@Minyus fix https://github.com/6syun9/twitter_manager/pull/6

**Comment by Minyus** [comment]
@6syun9 ありがとうございます。followed の値を取れるようになりました。

![image](https://user-images.githubusercontent.com/33908456/63518889-90c78480-c524-11e9-963f-cba4aca709cd.png)
